root: true
env:
  es2020: true
  node: true
parser: "@typescript-eslint/parser"
extends:
  - plugin:@typescript-eslint/recommended
  - eslint:recommended
  - plugin:prettier/recommended
rules:
  'no-unused-vars': 'off',
  "@typescript-eslint/no-unused-vars": "error"
